version: '3.1'

networks:
  zig-pg-demo-net:
    driver: bridge

services:

  db:
    image: postgres
    container_name: zig-pg-demo
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "25432:5432"
    networks:
      - zig-pg-demo-net

